---
# cofigure kubernetes nodes with users and access

- hosts: all
  become: true

  vars:
    remote_user_name: vagrant

  tasks:
    - name: Copy Sample Inventory to Vagrant user home
      copy:
        src: '/vagrant/files/sample-inventory'
        dest: "/home/{{ remote_user_name }}/inventory"
        mode: '0755'
      when: inventory_hostname == 'ansible-engine-1'